    AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM app that automatically invalidates CF distros when S3 content changes
Resources:
  CloudfrontInvalidator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      Runtime: python3.9
      CodeUri: s3://cloudfront-invalidator/57ea5269af4e8b55ad6a22ec4401b252
      Description: Invalidates content in a cloudfront distro when S3 content changes.
      MemorySize: 512
      Timeout: 30
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          - cloudfront:Get*
          - cloudfront:ListDistributions
          - s3:ListBucket
          - s3:HeadObject
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:DeleteObject
          - s3:ListObjects
          - s3:*
          - s3:PutObject
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
    Metadata:
      SamResourceId: CloudfrontInvalidator
Outputs:
  InvalidatorFunctionName:
    Description: The name of the lambda invalidator Function
    Value:
      Ref: CloudfrontInvalidator
